export const productsData = [
  {
    id: 1,
    name: "iphone14",
    price: "5,750,000",
    image: "iphone--14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 1,
    Popularity: 1,
  },
  {
    id: 2,
    name: "مچ بند شیائومی مدل Mi Band 8",
    price: "6,130,000",
    image: "Mi Band 8.jpg",
    brand: "شیائومی",
    type: "watch",
    saleNumber: 1,
    Popularity: 2,
  },
  {
    id: 3,
    name: "MacBook Pro MNWA3 2023",
    price: "7,250,000",
    image: "MacBook Pro MNWA3 2023.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 1,
    Popularity: 3,
  },
  {
    id: 4,
    name: "Redmi Note 11",
    price: "8,000,000",
    image: "redmeNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 2,
    Popularity: 4,
  },
  {
    id: 5,
    name: "ساعت هوشمند مدل K59pro",
    price: "9,000,000",
    image: "K59pro.jpg",
    brand: "ایسوس",
    type: "watch",
    saleNumber: 2,
    Popularity: 5,
  },
  {
    id: 6,
    name: "MacBook Air MGN63 2020",
    price: "10,000,000",
    image: "MacBook Air MGN63 2020.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 2,
    Popularity: 6,
  },
  {
    id: 7,
    name: "Galaxy A14",
    price: "11,000,000",
    image: "galaxyA14.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 3,
    Popularity: 7,
  },
  {
    id: 8,
    name: "ساعت هوشمند مدل T500",
    price: "12,000,000",
    image: "T500.jpg",
    brand: "اپل",
    type: "watch",
    saleNumber: 3,
    Popularity: 8,
  },
  {
    id: 9,
    name: "MacBook Air-B M2 2022",
    price: "13,000,000",
    image: "MacBook Air-B M2 2022.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 3,
    Popularity: 9,
  },
  {
    id: 10,
    name: "Y9a",
    price: "14,000,000",
    image: "Y9a.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 4,
    Popularity: 10,
  },
  {
    id: 11,
    name: "Vivobook 15 OLED",
    price: "15,000,000",
    image: "Vivobook 15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 4,
    Popularity: 11,
  },
  {
    id: 12,
    name: "iphone15",
    price: "16,000,000",
    image: "galaxyA14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 5,
    Popularity: 12,
  },
  {
    id: 13,
    name: "TUF Gaming F15",
    price: "17,000,000",
    image: "TUF Gaming F15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 5,
    Popularity: 13,
  },
  {
    id: 14,
    name: "Redmi Note 11 Pro Plus 5G",
    price: "18,000,000",
    image: "redmiNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 6,
    Popularity: 14,
  },
  {
    id: 15,
    name: "Galaxy S23",
    price: "19,000,000",
    image: "galaxyS23.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 7,
    Popularity: 15,
  },
  {
    id: 16,
    name: "Nova 11i",
    price: "20,000,000",
    image: "Nova11i.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 8,
    Popularity: 16,
  },
  {
    id: 17,
    name: "iphone14",
    price: "21,000,000",
    image: "iphone--14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 9,
    Popularity: 17,
  },
  {
    id: 18,
    name: "Redmi Note 11",
    price: "22,000,000",
    image: "redmeNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 10,
    Popularity: 18,
  },
  {
    id: 19,
    name: "Galaxy A14",
    price: "23,000,000",
    image: "galaxyA14.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 11,
    Popularity: 19,
  },
  {
    id: 20,
    name: "Y9a",
    price: "24,000,000",
    image: "Y9a.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 12,
    Popularity: 20,
  },
  {
    id: 21,
    name: "X515EP-EJ743-i7 16GB",
    price: "25,000,000",
    image: "X515EP-EJ743-i7 16GB.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 6,
    Popularity: 21,
  },
  {
    id: 22,
    name: "iphone14",
    price: "26,000,000",
    image: "iphone--14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 13,
    Popularity: 22,
  },
  {
    id: 23,
    name: "مچ بند شیائومی مدل Mi Band 8",
    price: "27,000,000",
    image: "Mi Band 8.jpg",
    brand: "شیائومی",
    type: "watch",
    saleNumber: 4,
    Popularity: 23,
  },
  {
    id: 24,
    name: "MacBook Pro MNWA3 2023",
    price: "28,000,000",
    image: "MacBook Pro MNWA3 2023.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 7,
    Popularity: 24,
  },
  {
    id: 25,
    name: "Redmi Note 11",
    price: "29,000,000",
    image: "redmeNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 14,
    Popularity: 25,
  },
  {
    id: 26,
    name: "ساعت هوشمند مدل K59pro",
    price: "30,000,000",
    image: "K59pro.jpg",
    brand: "ایسوس",
    type: "watch",
    saleNumber: 5,
    Popularity: 26,
  },
  {
    id: 27,
    name: "MacBook Air MGN63 2020",
    price: "65,000,000",
    image: "MacBook Air MGN63 2020.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 8,
    Popularity: 27,
  },
  {
    id: 28,
    name: "Galaxy A14",
    price: "32,000,000",
    image: "galaxyA14.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 15,
    Popularity: 28,
  },
  {
    id: 29,
    name: "ساعت هوشمند مدل T500",
    price: "33,000,000",
    image: "T500.jpg",
    brand: "اپل",
    type: "watch",
    saleNumber: 6,
    Popularity: 29,
  },
  {
    id: 30,
    name: "MacBook Air-B M2 2022",
    price: "34,000,000",
    image: "MacBook Air-B M2 2022.jpg",
    brand: "اپل",
    type: "laptop",
    saleNumber: 9,
    Popularity: 30,
  },
  {
    id: 31,
    name: "Y9a",
    price: "900,000",
    image: "Y9a.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 16,
    Popularity: 31,
  },
  {
    id: 32,
    name: "Vivobook 15 OLED",
    price: "800,000",
    image: "Vivobook 15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 10,
    Popularity: 32,
  },
  {
    id: 33,
    name: "iphone15",
    price: "700,000",
    image: "galaxyA14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 17,
    Popularity: 33,
  },
  {
    id: 34,
    name: "TUF Gaming F15",
    price: "600,000",
    image: "TUF Gaming F15.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 12,
    Popularity: 34,
  },
  {
    id: 35,
    name: "Redmi Note 11 Pro Plus 5G",
    price: "650,000",
    image: "redmiNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 18,
    Popularity: 35,
  },
  {
    id: 36,
    name: "Galaxy S23",
    price: "500,000",
    image: "galaxyS23.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 19,
    Popularity: 36,
  },
  {
    id: 37,
    name: "Nova 11i",
    price: "85,258,520",
    image: "Nova11i.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 20,
    Popularity: 37,
  },
  {
    id: 38,
    name: "iphone14",
    price: "45,256,852",
    image: "iphone--14.jpg",
    brand: "اپل",
    type: "mobile",
    saleNumber: 21,
    Popularity: 38,
  },
  {
    id: 39,
    name: "Redmi Note 11",
    price: "25,265,000",
    image: "redmeNote11.jpg",
    brand: "شیائومی",
    type: "mobile",
    saleNumber: 22,
    Popularity: 39,
  },
  {
    id: 40,
    name: "Galaxy A14",
    price: "55,236,000",
    image: "galaxyA14.jpg",
    brand: "سامسونگ",
    type: "mobile",
    saleNumber: 23,
    Popularity: 40,
  },
  {
    id: 41,
    name: "Y9a",
    price: "43,253,000",
    image: "Y9a.jpg",
    brand: "هواوی",
    type: "mobile",
    saleNumber: 24,
    Popularity: 41,
  },
  {
    id: 42,
    name: "X515EP-EJ743-i7 16GB",
    price: "300,000,000",
    image: "X515EP-EJ743-i7 16GB.jpg",
    brand: "ایسوس",
    type: "laptop",
    saleNumber: 13,
    Popularity: 42,
  },
];

export const itemsInNavFilter = [
  { id: 0, text: "تمام محصولات" },
  { id: 1, text: "محبوب ترین ها" },
  { id: 2, text: "گران ترین ها" },
  { id: 3, text: "ارزان ترین ها" },
];

export const menuItems = [
  {
    id: "1",
    href: "#",
    text: "خانه",
  },
  {
    id: "2",
    href: "#",
    text: "تلفن همراه",
  },
  {
    id: "3",
    href: "#",
    text: "لپ تاپ",
  },
  {
    id: "4",
    href: "#",
    text: "ساعت هوشمند",
  },
  {
    id: "5",
    href: "#",
    text: "درباره ی ما",
  },
  {
    id: "6",
    href: "#",
    text: "تماس با ما",
  },
];
